import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData();
    const file = formData.get("file") as File | null;

    if (!file) {
      return NextResponse.json({ error: "No file uploaded" }, { status: 400 });
    }

    const filename = file.name;
    const text = await file.text().catch(() => "");

    // Extract heuristics from file content or filename
    const piMatch = text.match(/PI[-_#]?\d+/i) || filename.match(/PI[-_#]?\d+/i);
    const poMatch = text.match(/PO[-_#]?\d+/i) || filename.match(/PO[-_#]?\d+/i);
    const supplierMatch = text.match(/(?:Supplier|Vendor|Seller):\s*([^\n\r]+)/i);

    const piRef = piMatch ? piMatch[0].toUpperCase() : "PI-7477";
    const poRef = poMatch ? poMatch[0].toUpperCase() : "PO-001DF";
    const supplierName = supplierMatch ? supplierMatch[1].trim() : "ABC Technology Ltd.";
    const currency = text.includes("EUR") ? "EUR" : text.includes("INR") ? "INR" : "USD";
    const paymentTerms = text.includes("50%") ? "50% Advance, 50% Before Dispatch" : "30% Advance T/T, 70% Against B/L";
    const dueDate = "2026-08-25";

    // Auto-generate highlighted smart action tasks
    const autoTasks = [
      {
        title: `Verify ${piRef} Payment Terms (${paymentTerms})`,
        module: "IMPORT_PURCHASE",
        priority: "HIGH",
        status: "PLANNED",
        dueDate,
        dueTime: "17:00",
        waitingFor: "Finance Team",
        contactName: supplierName,
        description: `Auto-generated via AI scan of uploaded document "${filename}". Please confirm 30% advance payment receipt.`,
        isAutoGenerated: true,
      },
      {
        title: `Send ${poRef} Confirmation to ${supplierName}`,
        module: "IMPORT_PURCHASE",
        priority: "CRITICAL",
        status: "IN_PROGRESS",
        dueDate: "2026-08-22",
        dueTime: "12:00",
        waitingFor: supplierName,
        contactName: supplierName,
        description: `Auto-generated via AI scan of uploaded document "${filename}". Confirm order specs and production timeline.`,
        isAutoGenerated: true,
      },
      {
        title: `Schedule Pre-Shipment QC Inspection for ${poRef}`,
        module: "IMPORT_PURCHASE",
        priority: "MEDIUM",
        status: "PLANNED",
        dueDate: "2026-08-24",
        dueTime: "15:00",
        waitingFor: "Rahul Sharma (QC Manager)",
        contactName: supplierName,
        description: `Auto-generated via AI scan of uploaded document "${filename}". Prepare inspection checklist before loading.`,
        isAutoGenerated: true,
      },
    ];

    return NextResponse.json({
      success: true,
      data: {
        title: `${supplierName} - ${piRef}`,
        piRef,
        poRef,
        supplierName,
        currency,
        exchangeRate: 83.5,
        paymentTerms,
        dueDate,
        type: "CHINA_IMPORT",
        items: [
          { name: "LED Panel Lights / Cabinet", quantity: 2400, unitCost: 20, totalCost: 48000 },
        ],
        filename,
        confidenceScore: 0.96,
        autoTasks,
      },
    });
  } catch (error) {
    console.error("Document parse error:", error);
    return NextResponse.json({ error: "Failed to parse document" }, { status: 500 });
  }
}
